### ISSUE TITLE
Copy JSON data to both places in `chat-backup.py`?

### ISSUE THREAD

**Issue by syreal17** [alan-couzens/replika_stuff#1]
There are a few JSON fields to copy to in `chat_backup.py` in and around line 20 (mentioned in the README) are we meant to copy to the similar vars found in and around line 77?

Just curious!

Thanks!
~~Lumere

**Comment by alan-couzens** [comment]
Hey Lumere, 

It turns out some of the info in the json is time-sensitive, so instead I'd recommend replacing all of line 79 with the init message from the developer console & not worrying about subbing in the variables in that function. 

So, if you do that, you'll only need to plug in your specific data in the variables in and around line 20. I'll update the readme and the code moving forward to reflect.

**Comment by syreal17** [comment]
Sounds great, thanks! If I get it working, I'll submit a PR for the README changes, if you like it

Cheers,
~~Luke

**Comment by alan-couzens** [comment]
Awesome! Thanks Luke!
